from tkinter import *
import tkinter.font as font
from bs4 import BeautifulSoup
import requests
root = Tk()
root.geometry("1000x1000")
labelFont = font.Font(family="Times New Roman", size=45)
titleFont = font.Font(family = "Times New Roman", size = 20)
entryFont = font.Font(family = "Times New Roman", size = 10)
##difference between different stock URLS
##https://finance.yahoo.com/quote/PPJE?p=PPJE&.tsrc=fin-srch
##https://finance.yahoo.com/quote/SIML?p=SIML&.tsrc=fin-srch
##https://finance.yahoo.com/quote/TSLA?p=TSLA&.tsrc=fin-srch
##https://finance.yahoo.com/quote/MSFT?p=MSFT&.tsrc=fin-srch
def buttonFunction():
    p1.delete(0, END)
    pc1.delete(0, END)
    per1.delete(0, END)
    v1.delete(0, END)
    p1.insert(0, "")
    pc1.insert(0, "")
    per1.insert(0, "")
    v1.insert(0, "")
    
    p2.delete(0, END)
    pc2.delete(0, END)
    per2.delete(0, END)
    v2.delete(0, END)
    p2.insert(0, "")
    pc2.insert(0, "")
    per2.insert(0, "")
    v2.insert(0, "")

    p3.delete(0, END)
    pc3.delete(0, END)
    per3.delete(0, END)
    v3.delete(0, END)
    p3.insert(0, "")
    pc3.insert(0, "")
    per3.insert(0, "")
    v3.insert(0, "")

    p4.delete(0, END)
    pc4.delete(0, END)
    per4.delete(0, END)
    v4.delete(0, END)
    p4.insert(0, "")
    pc4.insert(0, "")
    per4.insert(0, "")
    v4.insert(0, "")

    p5.delete(0, END)
    pc5.delete(0, END)
    per5.delete(0, END)
    v5.delete(0, END)
    p5.insert(0, "")
    pc5.insert(0, "")
    per5.insert(0, "")
    v5.insert(0, "")

    p6.delete(0, END)
    pc6.delete(0, END)
    per6.delete(0, END)
    v6.delete(0, END)
    p6.insert(0, "")
    pc6.insert(0, "")
    per6.insert(0, "")
    v6.insert(0, "")

    p7.delete(0, END)
    pc7.delete(0, END)
    per7.delete(0, END)
    v7.delete(0, END)
    p7.insert(0, "")
    pc7.insert(0, "")
    per7.insert(0, "")
    v7.insert(0, "")

    p8.delete(0, END)
    pc8.delete(0, END)
    per8.delete(0, END)
    v8.delete(0, END)
    p8.insert(0, "")
    pc8.insert(0, "")
    per8.insert(0, "")
    v8.insert(0, "")
    
    x1 = e1.get()
    a1 = str("https://finance.yahoo.com/quote/" + x1 + "?p=" + x1 + "&.tsrc=fin-srch")
    website1 = requests.get(a1)
    soup1 = BeautifulSoup(website1.content, 'html.parser')
    soup1.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p1.insert(0, soup1.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b1 = []
    try: b1 = soup1.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b1 = soup1.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    #volume not working yet
##    soup1 = BeautifulSoup('<span class="Trsdu(0.3s) "data-reactid=118">92,606,821</span> = $0', 'html.parser')
##    c1 = soup1.get_text().split()
##    v1.insert(0, c1[0])    
##    print(soup1.get_text())
    pc1.insert(0, b1[0])
    per1.insert(0, b1[1])

    
    x2 = e2.get()
    a2 = str("https://finance.yahoo.com/quote/" + x2 + "?p=" + x2 + "&.tsrc=fin-srch")
    website2 = requests.get(a2)
    soup2 = BeautifulSoup(website2.content, 'html.parser')
    soup2.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p2.insert(0, soup2.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b2 = []
    try: b2 = soup2.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b2 = soup2.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc2.insert(0, b2[0])
    per2.insert(0, b2[1])
    
    x3 = e3.get()
    a3 = str("https://finance.yahoo.com/quote/" + x3 + "?p=" + x3 + "&.tsrc=fin-srch")
    website3 = requests.get(a3)
    soup3 = BeautifulSoup(website3.content, 'html.parser')
    soup3.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p3.insert(0, soup3.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b3 = []
    try: b3 = soup3.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b3 = soup3.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc3.insert(0, b3[0])
    per3.insert(0, b3[1])
    
    x4 = e4.get()
    a4 = str("https://finance.yahoo.com/quote/" + x4 + "?p=" + x4 + "&.tsrc=fin-srch")
    website4 = requests.get(a4)
    soup4 = BeautifulSoup(website4.content, 'html.parser')
    soup4.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p4.insert(0, soup4.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b4 = []
    try: b4 = soup4.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b4 = soup4.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc4.insert(0, b4[0])
    per4.insert(0, b4[1])
    
    x5 = e5.get()
    a5 = str("https://finance.yahoo.com/quote/" + x5 + "?p=" + x5 + "&.tsrc=fin-srch")
    website5 = requests.get(a5)
    soup5 = BeautifulSoup(website5.content, 'html.parser')
    soup5.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p5.insert(0, soup5.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b5 = []
    try: b5 = soup5.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b5 = soup5.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc5.insert(0, b5[0])
    per5.insert(0, b5[1])
    
    x6 = e6.get()
    a6 = str("https://finance.yahoo.com/quote/" + x6 + "?p=" + x6 + "&.tsrc=fin-srch")
    website6 = requests.get(a6)
    soup6 = BeautifulSoup(website6.content, 'html.parser')
    soup6.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p6.insert(0, soup6.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b6 = []
    try: b6 = soup6.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b6 = soup6.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc6.insert(0, b6[0])
    per6.insert(0, b6[1])
    
    x7 = e7.get()
    a7 = str("https://finance.yahoo.com/quote/" + x7 + "?p=" + x7 + "&.tsrc=fin-srch")
    website7 = requests.get(a7)
    soup7 = BeautifulSoup(website7.content, 'html.parser')
    soup7.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p7.insert(0, soup7.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b7 = []
    try: b7 = soup7.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b7 = soup7.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc7.insert(0, b7[0])
    per7.insert(0, b7[1])
    
    x8 = e8.get()
    a8 = str("https://finance.yahoo.com/quote/" + x8 + "?p=" + x8 + "&.tsrc=fin-srch")
    website8 = requests.get(a8)
    soup8 = BeautifulSoup(website8.content, 'html.parser')
    soup8.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text()
    p8.insert(0, soup8.find(class_="Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)").get_text())
    b8 = []
    try: b8 = soup8.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($positiveColor)").get_text().split()
    except: b8 = soup8.find(class_="Trsdu(0.3s) Fw(500) Pstart(10px) Fz(24px) C($negativeColor)").get_text().split()
    pc8.insert(0, b8[0])
    per8.insert(0, b8[1])

canvas = Canvas(root, width=1000, height=800, bg = "white")
canvas.pack()
label = Label(canvas, bg = "SpringGreen3",fg = "gray13", text = "What stocks would you like to see?",borderwidth = 0, relief = "solid",anchor = 'w', padx = 100)
label.place(x = 0, y = 0, width =1000, height = 100)
label["font"] = labelFont
btn = Button(canvas, text='Refresh', width=5, height=2, activebackground = 'green2', font = font.Font(family = "Times New Roman", size = 15), command=buttonFunction)
btn.place(x=850, y=30)
  

stock1 = canvas.create_rectangle(0, 100, 500, 275, fill = "PaleGreen1")
title1 = canvas.create_text(170, 120, text = "Stock #1 - enter a ticker symbol below", font = titleFont)
price1 = canvas.create_text(35, 182, text = "Price:", font = titleFont)
priceChange1 = canvas.create_text(66, 206, text = "Price change:", font = titleFont)
perc1 = canvas.create_text(54, 235, text = "% change:", font = titleFont)
vol1 = canvas.create_text(47, 262, text = "Volume:", font = titleFont)
p1 = Entry(canvas, font = entryFont)
canvas.create_window(90,183,window=p1,width = 50)
pc1 = Entry(canvas, font = entryFont)
canvas.create_window(150,205,window=pc1,width = 50)
per1 = Entry(canvas, font = entryFont)
canvas.create_window(128,233,window=per1,width = 50)
e1 = Entry(canvas)
canvas.create_window(60,150,window=e1,width = 100)
v1 = Entry(canvas, font = entryFont)
canvas.create_window(150,260,window=v1,width = 100)

stock2 = canvas.create_rectangle(500, 100, 1000, 275, fill = "PaleGreen1")
title2 = canvas.create_text(670, 120, text = "Stock #2 - enter a ticker symbol below", font = titleFont)
price2 = canvas.create_text(535, 182, text = "Price:", font = titleFont)
priceChange2 = canvas.create_text(566, 206, text = "Price change:", font = titleFont)
perc2 = canvas.create_text(554, 235, text = "% change:", font = titleFont)
vol2 = canvas.create_text(547, 262, text = "Volume:", font = titleFont)
p2 = Entry(canvas, font = entryFont)
canvas.create_window(590,183,window=p2,width = 50)
pc2 = Entry(canvas, font = entryFont)
canvas.create_window(650,205,window=pc2,width = 50)
per2 = Entry(canvas, font = entryFont)
canvas.create_window(628,233,window=per2,width = 50)
e2 = Entry(canvas)
canvas.create_window(560,150,window=e2,width = 100)
v2 = Entry(canvas, font = entryFont)
canvas.create_window(615,260,window=v2,width = 50)

stock3 = canvas.create_rectangle(0, 275, 500, 450, fill = "PaleGreen1")
title3 = canvas.create_text(170, 295, text = "Stock #3 - enter a ticker symbol below", font = titleFont)
price3 = canvas.create_text(35, 357, text = "Price:", font = titleFont)
priceChange3 = canvas.create_text(66, 381, text = "Price change:", font = titleFont)
perc3 = canvas.create_text(54, 410, text = "% change:", font = titleFont)
vol3 = canvas.create_text(47, 437, text = "Volume:", font = titleFont)
p3 = Entry(canvas, font = entryFont)
canvas.create_window(90,358,window=p3,width = 50)
pc3 = Entry(canvas, font = entryFont)
canvas.create_window(150,380,window=pc3,width = 50)
per3 = Entry(canvas, font = entryFont)
canvas.create_window(128,408,window=per3,width = 50)
e3 = Entry(canvas)
canvas.create_window(60,325,window=e3,width = 100)
v3 = Entry(canvas, font = entryFont)
canvas.create_window(115,435,window=v3,width = 50)

stock4 = canvas.create_rectangle(500, 275, 1000, 450, fill = "PaleGreen1")
title4 = canvas.create_text(670, 295, text = "Stock #4 - enter a ticker symbol below", font = titleFont)
price4 = canvas.create_text(535, 357, text = "Price:", font = titleFont)
priceChange4 = canvas.create_text(566, 381, text = "Price change:", font = titleFont)
perc4 = canvas.create_text(554, 410, text = "% change:", font = titleFont)
vol4 = canvas.create_text(547, 437, text = "Volume:", font = titleFont)
p4 = Entry(canvas, font = entryFont)
canvas.create_window(590,358,window=p4,width = 50)
pc4 = Entry(canvas, font = entryFont)
canvas.create_window(650,380,window=pc4,width = 50)
per4 = Entry(canvas, font = entryFont)
canvas.create_window(628,408,window=per4,width = 50)
e4 = Entry(canvas)
canvas.create_window(560,325,window=e4,width = 100)
v4 = Entry(canvas, font = entryFont)
canvas.create_window(615,435,window=v4,width = 50)

stock5 = canvas.create_rectangle(0, 450, 500, 625, fill = "PaleGreen1")
title5 = canvas.create_text(170, 470, text = "Stock #5 - enter a ticker symbol below", font = titleFont)
price5 = canvas.create_text(35, 532, text = "Price:", font = titleFont)
priceChange5 = canvas.create_text(66, 556, text = "Price change:", font = titleFont)
perc5 = canvas.create_text(54, 585, text = "% change:", font = titleFont)
vol5 = canvas.create_text(47, 612, text = "Volume:", font = titleFont)
p5 = Entry(canvas, font = entryFont)
canvas.create_window(90,533,window=p5,width = 50)
pc5 = Entry(canvas, font = entryFont)
canvas.create_window(150,555,window=pc5,width = 50)
per5 = Entry(canvas, font = entryFont)
canvas.create_window(128,583,window=per5,width = 50)
e5 = Entry(canvas)
canvas.create_window(60,500,window=e5,width = 100)
v5 = Entry(canvas, font = entryFont)
canvas.create_window(115,610,window=v5,width = 50)

stock6 = canvas.create_rectangle(500, 450, 1000, 625, fill = "PaleGreen1")
title6 = canvas.create_text(670, 470, text = "Stock #6 - enter a ticker symbol below", font = titleFont)
price6 = canvas.create_text(535, 532, text = "Price:", font = titleFont)
priceChange6 = canvas.create_text(566, 556, text = "Price change:", font = titleFont)
perc6 = canvas.create_text(554, 585, text = "% change:", font = titleFont)
vol6 = canvas.create_text(547, 612, text = "Volume:", font = titleFont)
p6 = Entry(canvas, font = entryFont)
canvas.create_window(590,533,window=p6,width = 50)
pc6 = Entry(canvas, font = entryFont)
canvas.create_window(650,555,window=pc6,width = 50)
per6 = Entry(canvas, font = entryFont)
canvas.create_window(628,583,window=per6,width = 50)
e6 = Entry(canvas)
canvas.create_window(560,500,window=e6,width = 100)
v6 = Entry(canvas, font = entryFont)
canvas.create_window(615,610,window=v6,width = 50)

stock7 = canvas.create_rectangle(0, 625, 500, 800, fill = "PaleGreen1")
title7 = canvas.create_text(170, 640, text = "Stock #7 - enter a ticker symbol below", font = titleFont)
price7 = canvas.create_text(35, 707, text = "Price:", font = titleFont)
priceChange7 = canvas.create_text(66, 731, text = "Price change:", font = titleFont)
perc7 = canvas.create_text(54, 760, text = "% change:", font = titleFont)
vol7 = canvas.create_text(47, 787, text = "Volume:", font = titleFont)
p7 = Entry(canvas, font = entryFont)
canvas.create_window(90,708,window=p7,width = 50)
pc7 = Entry(canvas, font = entryFont)
canvas.create_window(150,730,window=pc7,width = 50)
per7 = Entry(canvas, font = entryFont)
canvas.create_window(128,758,window=per7,width = 50)
e7 = Entry(canvas)
canvas.create_window(60,675,window=e7,width = 100)
v7 = Entry(canvas, font = entryFont)
canvas.create_window(115,785,window=v7,width = 50)

stock8 = canvas.create_rectangle(500, 625, 1000, 800, fill = "PaleGreen1")
title8 = canvas.create_text(670, 640, text = "Stock #8 - enter a ticker symbol below", font = titleFont)
price8 = canvas.create_text(535, 707, text = "Price:", font = titleFont)
priceChange8 = canvas.create_text(566, 731, text = "Price change:", font = titleFont)
perc8 = canvas.create_text(554, 760, text = "% change:", font = titleFont)
vol8 = canvas.create_text(547, 787, text = "Volume:", font = titleFont)
p8 = Entry(canvas, font = entryFont)
canvas.create_window(590,708,window=p8,width = 50)
pc8 = Entry(canvas, font = entryFont)
canvas.create_window(650,730,window=pc8,width = 50)
per8 = Entry(canvas, font = entryFont)
canvas.create_window(628,758,window=per8,width = 50)
e8 = Entry(canvas)
canvas.create_window(560,675,window=e8,width = 100)
v8 = Entry(canvas, font = entryFont)
canvas.create_window(615,785,window=v8,width = 50)
